apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinicapp-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clinicapp
  template:
    metadata:
      labels:
        app: clinicapp
    spec:
      containers:
      - name: clinicapp-container
        image: clinicapp:v7
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development.Kubernetes"
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: clinicapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: clinicapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapp-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificationapp
  template:
    metadata:
      labels:
        app: notificationapp
    spec:
      containers:
      - name: notifictionapp-container
        image: notificationapp:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development.Kubernetes"
        imagePullPolicy: Never